name: Build & Deploy via GHCR (AlphaVPS)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Needed for GHCR push/pull using GITHUB_TOKEN
permissions:
  contents: read
  packages: write

env:
  # IMPORTANT: GHCR image names must be lowercase
  GHCR_IMAGE: ghcr.io/xxx00xxx33/tushare_etf_mcp
  # Your VPS compose paths (from docker inspect labels)
  APP_DIR: /opt/tushare_etf_mcp
  COMPOSE_MAIN: /opt/tushare_etf_mcp/compose.yml
  COMPOSE_OVERRIDE: /opt/tushare_etf_mcp/compose.ghcr.override.yml

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.vars.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute image tag
        id: vars
        run: |
          echo "image_tag=sha-${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.GHCR_IMAGE }}:latest
            ${{ env.GHCR_IMAGE }}:${{ steps.vars.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: [self-hosted, alphavps]
    steps:
      - name: Login to GHCR (on VPS runner)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy on AlphaVPS
        env:
          IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
        run: |
          set -euo pipefail

          cd "${APP_DIR}"

          echo "[1/5] Sanity check compose files"
          test -f "${COMPOSE_MAIN}"
          test -f "${COMPOSE_OVERRIDE}"

          echo "[2/5] Pull exact image tag: ${IMAGE_TAG}"
          export IMAGE_TAG="${IMAGE_TAG}"
          docker compose -f "${COMPOSE_MAIN}" -f "${COMPOSE_OVERRIDE}" pull

          echo "[3/5] Recreate containers (NO build on VPS)"
          docker compose -f "${COMPOSE_MAIN}" -f "${COMPOSE_OVERRIDE}" up -d --no-build --force-recreate --remove-orphans

          echo "[4/5] Health check"
          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8830/health || true)
          test "${status_code}" = "200"

          echo "[5/5] Status"
          docker compose -f "${COMPOSE_MAIN}" -f "${COMPOSE_OVERRIDE}" ps
          docker image prune -f
